# Generated by Django 5.0.10 on 2026-01-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=200, verbose_name="书名")),
                ("content", models.TextField(verbose_name="书评内容")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="评分(1~5)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "书评",
                "verbose_name_plural": "书评",
                "db_table": "reviews_review",
            },
        ),
    ]
