# Generated by Django 5.0.10 on 2026-01-12 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.BigIntegerField(
                        default=0,
                        help_text="当前可用金币数量，单位：个",
                        verbose_name="金币余额",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
                "db_table": "wallet",
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_amount",
                    models.BigIntegerField(
                        help_text="正数表示增加，负数表示减少", verbose_name="变动数量"
                    ),
                ),
                ("balance_after", models.BigIntegerField(verbose_name="变动后余额")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RECHARGE", "充值入账（支付）"),
                            ("PURCHASE", "购买扣减"),
                            ("RENEW", "会员续费扣减"),
                            ("ADMIN_RECHARGE", "管理员充值"),
                            ("ADMIN_DEDUCT", "管理员扣减"),
                        ],
                        max_length=30,
                        verbose_name="流水类型",
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        help_text="如 RECHARGE_ORDER / PURCHASE_ORDER / ADMIN",
                        max_length=30,
                        verbose_name="关联业务类型",
                    ),
                ),
                (
                    "ref_id",
                    models.BigIntegerField(
                        help_text="可记录订单ID；管理员操作可记录管理员ID",
                        verbose_name="关联业务ID",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        help_text="管理员操作必填：充值/扣减原因",
                        max_length=200,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        help_text="管理员操作时记录管理员账号；系统自动流水可为空",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coin_operator_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coin_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "金币流水",
                "verbose_name_plural": "金币流水",
                "db_table": "coin_transaction",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="idx_tx_user_time"
                    ),
                    models.Index(fields=["ref_type", "ref_id"], name="idx_tx_ref"),
                ],
            },
        ),
    ]
