# Generated by Django 5.0 on 2026-01-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("action", "动作"),
                            ("sci", "科幻"),
                            ("comedy", "喜剧"),
                            ("love", "爱情"),
                            ("crime", "犯罪"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        verbose_name="评分",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=8, verbose_name="价格"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                (
                    "is_hot",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="热门"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
