# Generated by Django 5.0 on 2026-01-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="片名")),
                (
                    "year",
                    models.PositiveIntegerField(default=2020, verbose_name="年份"),
                ),
            ],
            options={
                "permissions": [
                    ("publish_movie", "可以发布电影"),
                    ("export_movie", "可以导出电影"),
                ],
            },
        ),
    ]
