# Generated by Django 5.0.10 on 2026-01-12 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "登录"),
                            ("MFA", "二次验证"),
                            ("REGISTER", "注册"),
                            ("RESET_PASSWORD", "找回密码"),
                        ],
                        max_length=30,
                        verbose_name="用途",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        help_text="例如：SMS / EMAIL",
                        max_length=20,
                        verbose_name="发送渠道",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        help_text="邮箱/手机号等接收地址",
                        max_length=191,
                        verbose_name="接收方",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="只保存验证码哈希值，不保存明文",
                        max_length=255,
                        verbose_name="验证码哈希",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="验证码被成功使用后写入时间（一次性）",
                        null=True,
                        verbose_name="使用时间",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="用于限制暴力尝试", verbose_name="尝试次数"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True,
                        help_text="IPv4/IPv6",
                        max_length=45,
                        null=True,
                        verbose_name="请求IP",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="用于风控识别",
                        max_length=64,
                        null=True,
                        verbose_name="设备ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "验证码记录",
                "verbose_name_plural": "验证码记录",
                "db_table": "auth_otp",
                "indexes": [
                    models.Index(
                        fields=["receiver", "purpose"], name="idx_otp_receiver_purpose"
                    ),
                    models.Index(fields=["created_at"], name="idx_otp_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identity_type",
                    models.CharField(
                        choices=[
                            ("USERNAME", "用户名"),
                            ("EMAIL", "邮箱"),
                            ("PHONE", "手机号"),
                        ],
                        help_text="用户名/邮箱/手机号",
                        max_length=20,
                        verbose_name="身份类型",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="用户名 / 邮箱 / 手机号",
                        max_length=191,
                        verbose_name="登录标识",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="主身份用于默认展示与主登录方式标记",
                        verbose_name="是否主身份",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="邮箱/手机号验证码校验通过后置为 True",
                        verbose_name="是否已验证",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户登录身份",
                "verbose_name_plural": "用户登录身份",
                "db_table": "user_identity",
            },
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("WECHAT", "微信"), ("QQ", "QQ")],
                        max_length=20,
                        verbose_name="第三方平台",
                    ),
                ),
                (
                    "open_id",
                    models.CharField(
                        blank=True,
                        help_text="第三方平台用户唯一标识（可能为空）",
                        max_length=191,
                        null=True,
                        verbose_name="OpenID",
                    ),
                ),
                (
                    "union_id",
                    models.CharField(
                        blank=True,
                        help_text="跨应用统一标识（可能为空）",
                        max_length=191,
                        null=True,
                        verbose_name="UnionID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="头像地址"
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近登录时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "第三方账号绑定",
                "verbose_name_plural": "第三方账号绑定",
                "db_table": "oauth_account",
                "indexes": [
                    models.Index(fields=["user"], name="idx_oauth_user"),
                    models.Index(fields=["provider"], name="idx_oauth_provider"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "open_id"), name="uniq_provider_openid"
            ),
        ),
        migrations.AddConstraint(
            model_name="oauthaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "union_id"), name="uniq_provider_unionid"
            ),
        ),
        migrations.AddIndex(
            model_name="useridentity",
            index=models.Index(fields=["user"], name="idx_identity_user"),
        ),
        migrations.AddIndex(
            model_name="useridentity",
            index=models.Index(
                fields=["identity_type", "identifier"], name="idx_identity_lookup"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useridentity",
            unique_together={("identity_type", "identifier")},
        ),
    ]
