# Generated by Django 5.0.10 on 2026-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action"),
                            ("DRAMA", "Drama"),
                            ("COMEDY", "Comedy"),
                            ("SCI_FI", "Sci-Fi"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年份")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="评分"
                    ),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="热门")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "db_table": "movies_movie",
            },
        ),
    ]
