# Generated by Django 5.0.10 on 2026-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("overview", models.TextField(blank=True, verbose_name="简介")),
                (
                    "release_date",
                    models.DateField(blank=True, null=True, verbose_name="上映日期"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, default=0.0, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "db_table": "movies_movie",
            },
        ),
    ]
