# Generated by Django 5.0.10 on 2026-01-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="电影名称")),
                (
                    "original_title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="原片名"
                    ),
                ),
                (
                    "release_year",
                    models.IntegerField(blank=True, null=True, verbose_name="上映年份"),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("FREE", "免费"),
                            ("BUY_ONLY", "仅购买"),
                            ("BUY_OR_VIP", "购买或会员"),
                        ],
                        max_length=20,
                        verbose_name="观看方式",
                    ),
                ),
                (
                    "price_coin",
                    models.BigIntegerField(
                        default=0, help_text="0 表示免费", verbose_name="价格（金豆）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("ONLINE", "上架"),
                            ("OFFLINE", "下架"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上架时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "db_table": "movie",
            },
        ),
        migrations.CreateModel(
            name="MovieAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("COVER", "封面"),
                            ("VIDEO", "视频"),
                            ("POSTER", "海报"),
                        ],
                        max_length=20,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "asset_url",
                    models.CharField(max_length=500, verbose_name="资源地址"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否主资源"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序值")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.movie",
                        verbose_name="电影",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影资源",
                "verbose_name_plural": "电影资源",
                "db_table": "movie_asset",
            },
        ),
        migrations.CreateModel(
            name="MovieDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synopsis", models.TextField(verbose_name="剧情简介")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="片长（分钟）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.movie",
                        verbose_name="电影",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影详情",
                "verbose_name_plural": "电影详情",
                "db_table": "movie_detail",
            },
        ),
    ]
