# Generated by Django 5.0.10 on 2026-01-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(verbose_name="评分(1~5)")),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "author_display",
                    models.CharField(
                        default="匿名用户", max_length=80, verbose_name="作者展示名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
                "db_table": "reviews_review",
            },
        ),
    ]
