# Generated by Django 5.0 on 2026-01-10 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="导演姓名"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="国家/地区"
                    ),
                ),
            ],
            options={
                "verbose_name": "导演",
                "verbose_name_plural": "导演",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影类型",
                "verbose_name_plural": "电影类型",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="标签名"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="电影标题")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.9,
                        max_digits=8,
                        verbose_name="价格",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "A级（普通）"),
                            (2, "S级（重点）"),
                            (3, "SS级（王牌）"),
                        ],
                        default=1,
                        verbose_name="运营等级",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已上架"),
                ),
                ("stock", models.IntegerField(default=100, verbose_name="库存")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.director",
                        verbose_name="导演",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.genre",
                        verbose_name="类型",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="movies.tag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "ordering": ["-created_at"],
            },
        ),
    ]
