# Generated by Django 5.0.10 on 2026-01-12 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_coin", models.BigIntegerField(verbose_name="订单总金币")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "已创建"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "购买订单",
                "verbose_name_plural": "购买订单",
                "db_table": "purchase_order",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_coin", models.BigIntegerField(verbose_name="购买价格（金豆）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.purchaseorder",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单项",
                "verbose_name_plural": "订单项",
                "db_table": "purchase_order_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="授权时间"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.purchaseorderitem",
                        verbose_name="订单项",
                    ),
                ),
            ],
            options={
                "verbose_name": "购买授权",
                "verbose_name_plural": "购买授权",
                "db_table": "purchase_license",
                "unique_together": {("user", "movie")},
            },
        ),
    ]
