# Generated by Django 5.0 on 2026-01-08 09:00

import django.db.models.deletion
import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="标题"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=movies.models.movie_cover_path,
                        verbose_name="封面图",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MoviePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=movies.models.movie_photo_path, verbose_name="剧照"
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=50, verbose_name="说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影剧照",
                "verbose_name_plural": "剧照管理",
                "ordering": ["-created_at"],
            },
        ),
    ]
