# Generated by Django 5.0 on 2026-01-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="电影标题"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.9,
                        max_digits=8,
                        verbose_name="原价",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        default=0,
                        help_text="0~90，表示打折百分比，例如 20 表示打 8 折",
                        verbose_name="折扣(%)",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.9,
                        max_digits=8,
                        verbose_name="最终价(系统计算)",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已上架"),
                ),
                (
                    "risk_level",
                    models.IntegerField(
                        choices=[(1, "低风险"), (2, "中风险"), (3, "高风险")],
                        default=1,
                        verbose_name="风控等级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_movies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影商品",
                "verbose_name_plural": "电影商品",
                "ordering": ["-created_at"],
            },
        ),
    ]
