# Generated by Django 5.0 on 2026-01-10 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=50, verbose_name="导演"),
                ),
            ],
            options={
                "verbose_name": "导演",
                "verbose_name_plural": "导演",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="类型"),
                ),
            ],
            options={
                "verbose_name": "类型",
                "verbose_name_plural": "类型",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="片名"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.9,
                        max_digits=8,
                        verbose_name="价格",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1, default=7.5, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "草稿"),
                            (2, "待上架"),
                            (3, "已上架"),
                            (4, "已下架"),
                        ],
                        default=2,
                        verbose_name="运营状态",
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="用于列表页图片预览（可为空）",
                        verbose_name="海报URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_movies_changelist",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.director",
                        verbose_name="导演",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.genre",
                        verbose_name="类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
                "ordering": ["-created_at"],
            },
        ),
    ]
