# Generated by Django 5.0 on 2026-01-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="导演名"),
                ),
            ],
            options={
                "verbose_name": "导演",
                "verbose_name_plural": "导演管理",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="标题"
                    ),
                ),
                (
                    "category",
                    models.CharField(db_index=True, max_length=20, verbose_name="分类"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="上架"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=1,
                        default=0,
                        max_digits=3,
                        verbose_name="评分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="movies.director",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影管理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieSKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition", models.CharField(max_length=20, verbose_name="版本")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="价格"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影SKU",
                "verbose_name_plural": "SKU管理",
            },
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["category", "is_active"], name="idx_movie_cat_active"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["is_active", "-created_at"], name="idx_movie_active_ct"
            ),
        ),
        migrations.AddIndex(
            model_name="moviesku",
            index=models.Index(
                fields=["movie", "edition"], name="idx_sku_movie_edition"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviesku",
            unique_together={("movie", "edition")},
        ),
    ]
