# Generated by Django 5.0 on 2026-01-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="产地名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "产地",
                "verbose_name_plural": "产地",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "电影分类",
                "verbose_name_plural": "电影分类",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="语言名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "语言",
                "verbose_name_plural": "语言",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_cn", models.CharField(max_length=100, verbose_name="中文名")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=100, verbose_name="英文名"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="movies/people/",
                        verbose_name="头像",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="简介")),
            ],
            options={
                "verbose_name": "演职人员",
                "verbose_name_plural": "演职人员",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_cn",
                    models.CharField(max_length=200, verbose_name="译名/中文名"),
                ),
                (
                    "title_original",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="片名/原名"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="URL 标识"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="年代")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=50, verbose_name="字幕"),
                ),
                ("release_date", models.DateField(verbose_name="上映日期")),
                ("publish_date", models.DateField(verbose_name="发布时间")),
                (
                    "imdb_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="IMDb 评分",
                    ),
                ),
                (
                    "imdb_votes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="IMDb 评分人数"
                    ),
                ),
                (
                    "douban_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="豆瓣评分",
                    ),
                ),
                (
                    "douban_votes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="豆瓣评分人数"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(verbose_name="片长(分钟)"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="简介")),
                (
                    "cover",
                    models.ImageField(upload_to="movies/covers/", verbose_name="封面"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="价格"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                (
                    "is_on_sale",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                ("is_hot", models.BooleanField(default=False, verbose_name="是否热门")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.country",
                        verbose_name="产地",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.genre",
                        verbose_name="类别",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movies.language",
                        verbose_name="语言",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影",
            },
        ),
        migrations.CreateModel(
            name="MovieCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("writer", "Writer"),
                            ("actor", "Actor"),
                        ],
                        max_length=20,
                        verbose_name="角色类型",
                    ),
                ),
                (
                    "sort",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="movies.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="movies.person",
                        verbose_name="演职人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "电影演职人员",
                "verbose_name_plural": "电影演职人员",
                "ordering": ["role", "sort", "id"],
            },
        ),
    ]
