# Generated by Django 5.0.10 on 2026-01-12 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("MONTH", "月卡"), ("YEAR", "年卡")],
                        max_length=20,
                        verbose_name="会员类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "生效中"),
                            ("GRACE", "宽限期"),
                            ("EXPIRED", "已过期"),
                        ],
                        max_length=20,
                        verbose_name="会员状态",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="开始时间")),
                ("end_at", models.DateTimeField(verbose_name="结束时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "会员",
                "verbose_name_plural": "会员",
                "db_table": "membership",
            },
        ),
    ]
